language: python
python:
  - '2.7'
  - '3.6'
  - 'pypy3'
install: pip install -r requirements.txt -r requirements-dev.txt
dist: trusty
os: linux
script: coverage -m unittest discover -v
after_success:
  - coveralls
env:
  global:
  - secure: JcD/1ag/fTNkygaavf5jcRkQiJDgIyrtL4F00sWYCpEyBN6i1p1++0oRtXvS/EHVFNqPB0VDOeiX0LEp3GJV1tNPizyqQOrnOSl6+QUfCiy8Pz2tP5olq+6EuQqp68oNqokwlZraDCk8QxJhnitWsukhZhuf7dQBfluoTj/EEAN/uNrG7hjwTUvQnKOlSkF5ry01gCigffFwWZ9ZiTUauvV+6gmoG7xeDiwvsIlf5S0XQmtJWTWAVYdUSqt8X4qfwiamQuKNHKNPQcqMqRGhKgFRp+uCpCcU5jJqrdNmq2/w7ebbWYAqZ0MM6zarN/J+4/K4OglUm8PniFbSiNmCA1G1wQRlN7Kn61RD1T+Ruj6TIOLndKy8W+zK/yFUIejTPBaolVQ+YMv11WdqOD8rWAFGXNLk30+miV78dMlRClqF4sEO4Lz0eX1tzTri6IUTrTUtpCNvshWVGGRo3Mxlxp7ZOAxgka7I5xZ4RPiyUCaKZM8xuIurg6egfrbLKlmRTIkUx6dvZNPDiuY2ENyl/yyAbrdGpPZiNtmAyAmXmhGh8cHiGqJ2QYeKtfvgKWYSiXClKGlJm/fQcmLYfo/fcruQejOXc4M3Nt/YsGxFQT8Tgw0APAwJqlMtniwK4dRVclk0rzNSVqCl1bTKViDZ5SOkrO7tTeh5TrerN8P3esc=
  - secure: MR4a61tTCGo0OuMLlh+41xbF+xu2scIoGKLdjHbU3YQFk9LCwZpDHcFw8M3x00BOOYf6DiJvn3+kMqNsJqUths4fFdSAVZcsYpo2XxQwAVD2nB3SSmYbpL/uys8lluXSNj/ZcbG7HcLxq7388wNb15le+8/hH69Q9DDW8NELRThuSyyLJtvPRn9yIuMCekwxoT5W/lxFZsQ362TpWnKwVWRVgbFkHHNysgRyaIyKbjdQdmnDWMrmKLDRcn3olk4kF5FGeezVb5gip//mrWoPOpzgscD3c1HgC/BE9LHoh/InfMiajnRj1UCfyB+n+FrCrKjRa/XOjFg3Z7pOa93wGsszo8TbuFHG/lAJlivzUnHhCFH3Zl44dhXNFWnV0+wkH4CJ22NQ73bT/PAy6j444mPZzbI9iHIrfhwPigaLWZzZtyvS8emkVtwEyrD0rBNgKF2BR4ALGghOBXR3a8UHSSXXk6yPbjLZ+LKo/r+qJpFYbBOX+hnlVheMEsJEU6lcX8+YPaHnFmdbShaAfE8zQ1hnRFanXt10G7zLomF5y/GeEcF83w2i/DtkkIehSpz71KcyD2WBnbOQozpcMsx6gDaQCkOhfKavtgL0Vrtlb6mgdD1gG4azkLcqrPs+m4iOIz0dm1hppbnGVlwAFtFFLDkvtnUcmNtTk6aFYOtxaCo=
